global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Use o nome do serviço, não localhost
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'application'
    static_configs:
      - targets: ['app:3000'] # Adiciona a aplicação Express na porta 3000